before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: CDYkEet5LlmD1/RcaGjjhTIA2HlIvqMA1+FxCCB3skChjifazBdXKu2RtSufRBW8vrs7hu+suVXQVVaNICAC4WpjiMLoahtDrkrdrZjAYploPHD297vEWXPI6GU7gM15ydCTpC8aqF1bsNqy1jRdKH1CxaOZt0aBurfH9D7m1uVyQAA0tdg5cFvpb8dDjlNuT9pbf9oOXzuUfTtJGLxcWqtYoemxzkRaxkXam4/o7QEBRGhZv92rD+CUuabI2k6oEdMYg2uA0ndAToyOKqI9dTEWCbV/zo7yI8VN1qNwfLpVBf9iQQgL6ecfb4FTM8dQb+6wTe3WFIen6ce8ts1wHFLYBRwo81VeXtrtn7wAsUBsMffpulcw0j3NbQGtlDfTQvXVL/Y4mNJ0nyTP5yvj7iCY4Eu+XR9/B8Gmd+NXRY9PqOSlJgNzzCDL4WP5W70V8XYdP84qbRPz5RakuGnCK+15EreTdCyi1+lVdDigIrAuaosZcYK2EPN2vwqhg81Kb1WH1EshXrN/8t7N86WoDnjbdRNONFth1l9FGul+FgVtW1ezNbVA4Ukw8oz5LVlee8sdaJm8Es4TRyEfy4bNScQUPg4r3/eAQ9RbOwSzUf+HFdshLs2BReggX2mabdvS0wWNIbDRHjqUPJR9vJMeUZJrY4S55pXL8wWze7ais7o= # CRYPTO_AES_KEY
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
